vich_uploader:
  db_driver: orm
  storage: file_system
  mappings:
    image_file:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
    metadonnees_file:
      uri_prefix: /uploads/metadonnees
      upload_destination: '%kernel.project_dir%/public/uploads/metadonnees'